name: Auto Sync TRSS Updates

on:
  schedule:
    - cron: '0 0 * * *'    # 08:00 北京时间
    - cron: '0 6 * * *'    # 14:00 北京时间
    - cron: '0 12 * * *'   # 20:00 北京时间
    - cron: '0 18 * * *'   # 02:00 北京时间
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TRSS branch
        uses: actions/checkout@v4
        with:
          ref: TRSS
          fetch-depth: 0

      - name: Add TRSS remote and fetch
        run: |
          git remote | grep trss || git remote add trss https://github.com/TimeRainStarSky/Yunzai.git
          git fetch trss

      - name: Merge updates
        id: merge
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          OUTPUT=$(git merge trss/main --no-edit --allow-unrelated-histories 2>&1 || true)
          echo "$OUTPUT"
          echo "merge_result<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          git push origin TRSS || true

      - name: Send DingTalk notification
        if: always()
        run: |
          STATUS="${{ job.status }}"
          REPO="${{ github.repository }}"
          OUTPUT=$(echo "${{ steps.merge.outputs.merge_result }}" | tail -n 10)
          curl -s -X POST "${{ secrets.DINGTALK_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
                "msgtype": "text",
                "text": {
                  "content": "BiliBili【'"${REPO}"'】TRSS 同步任务完成。\n状态：'"${STATUS}"'\n最近输出：\n'"${OUTPUT}"'"
                }
              }'
